### ISSUE TITLE
How to handle values lower than LOD? 

### ISSUE THREAD

**Issue by Shicheng-Guo** [jackgisby/longitudinal_olink_proteomics#2]
Hi Jack, 

I am wondering what's recommendation to handle values lower than LOD? set to NA, set to LOD or just as it is? or we have better approach to handle values which are lower than LOD? 

Thanks. 

Shicheng

**Comment by jackgisby** [comment]
Hi Shicheng,

Apologies for the late response. 

This page has a useful discussion of values below LOD: https://www.olink.com/faq/how-is-the-limit-of-detection-lod-estimated-and-handled/

Olink's LOD is quite conservative - being estimated from the estimated background + three standard deviations.

We used the actual values below LOD, rather than removing them or replacing them with something else. If using this approach, it might be a good idea to remove assays from the analysis that have high levels of missingness - e.g. you could remove assays for which >50% of samples are <LOD.
