### ISSUE TITLE
How to handle olink outliers?

### ISSUE THREAD

**Issue by Shicheng-Guo** [jackgisby/longitudinal_olink_proteomics#3]
Hi Jack, 
I am wondering do we have a best strategy to handle outliers?
Thanks.
Shicheng

**Comment by jackgisby** [comment]
Hi Shicheng,

I don't think there's a single best approach to remove outlying samples. Outliers could be caused by some sort of technical issue with the sample, in which case we probably want to remove it. Alternatively, there could be a biological explanation for the difference, which might warrant further investigation.

I would recommend doing a few different checks on the data, for instance:
- Generate boxplots of expression values, for each sample
- We also used RLE plots: https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0191629
- Do principal components analysis, check if there are distinct groups of samples and/or clear outliers
